server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #eureka不像注册中心注册自己
    fetch-registry: false #false表示自己就是服务中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机
#      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # enable-self-preservation: true  eureka的自我保护机制，默认开启
#     defaultZone: http://eureka7001.com:7001/eureka/