server:
  port: 8901
spring:
  application:
    name: stream-cloud-kafka-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: test1    #消息发往的目的地  这个可以定义多个
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要 application/json
  datasource:
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  task:
    execution:
      pool:
        core-size: 10
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8901.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址